# Generated by Django 5.1 on 2024-08-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='direction',
            field=models.CharField(default=1, max_length=255, verbose_name='Направление'),
            preserve_default=False,
        ),
    ]
